name: Update Coverage on Readme
on:
  push:
    branches:
      - test-branch

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  update-coverage-on-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Pytest coverage comment
        if: ${{ github.ref == 'refs/heads/main' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@4a4889e6085d4e19fd19bf4a763c83d5332c8d06 # main
        with:
          hide-comment: true
          pytest-coverage-path: ./data/pytest-coverage_4.txt

      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          COVERAGE_CONTENT: ${{ steps.coverageComment.outputs.content }}
        run: |
          python3 - <<'EOF'
          import os, re
          content = os.environ['COVERAGE_CONTENT']
          begin = '<!-- Pytest Coverage Comment:Begin -->'
          end = '<!-- Pytest Coverage Comment:End -->'
          replacement = f'{begin}\n{content}\n{end}'
          with open('./README.md', 'r') as f:
              readme = f.read()
          new_readme = re.sub(
              re.escape(begin) + r'.*?' + re.escape(end),
              replacement,
              readme,
              flags=re.DOTALL
          )
          with open('./README.md', 'w') as f:
              f.write(new_readme)
          EOF

      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}
