name: Update Coverage in README
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '.github/**'
      - 'data/**'
      - 'dist/**'

permissions:
  contents: read

jobs:
  update-coverage-in-readme:
    name: Update Coverage in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: NPM Cache
        id: npm-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Check Format
        run: npm run format-check

      - name: Check Lint
        run: npm run lint

      - name: Check Build
        run: npm run build

      - name: Run Tests
        run: npm run test:coverage

      - name: Jest Coverage Comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@58072a21b8b7f84d36a6e21b5d9a0cad08bc9d75 # main
        with:
          hide-comment: true
          coverage-summary-path: ./coverage/coverage-summary.json
          junitxml-path: ./coverage/junit.xml

      - name: Check the output coverage
        env:
          COVERAGE: ${{ steps.coverageComment.outputs.coverage }}
          COLOR: ${{ steps.coverageComment.outputs.color }}
          SUMMARY_HTML: ${{ steps.coverageComment.outputs.summaryHtml }}
          TESTS: ${{ steps.coverageComment.outputs.tests }}
          SKIPPED: ${{ steps.coverageComment.outputs.skipped }}
          FAILURES: ${{ steps.coverageComment.outputs.failures }}
          ERRORS: ${{ steps.coverageComment.outputs.errors }}
          TIME: ${{ steps.coverageComment.outputs.time }}
          LINES: ${{ steps.coverageComment.outputs.lines }}
          BRANCHES: ${{ steps.coverageComment.outputs.branches }}
          FUNCTIONS: ${{ steps.coverageComment.outputs.functions }}
          STATEMENTS: ${{ steps.coverageComment.outputs.statements }}
          COVERAGE_HTML: ${{ steps.coverageComment.outputs.coverageHtml }}
        run: |
          echo "Summary Report"
          echo "Coverage Percentage - $COVERAGE"
          echo "Coverage Color - $COLOR"
          echo "Summary Html - $SUMMARY_HTML"

          echo "JUnit Report"
          echo "tests - $TESTS"
          echo "skipped - $SKIPPED"
          echo "failures - $FAILURES"
          echo "errors - $ERRORS"
          echo "time - $TIME"

          echo "Coverage Report"
          echo "lines - $LINES"
          echo "branches - $BRANCHES"
          echo "functions - $FUNCTIONS"
          echo "statements - $STATEMENTS"
          echo "coverage - $COVERAGE"
          echo "color - $COLOR"
          echo "Coverage Html - $COVERAGE_HTML"

      - name: Create the badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@0e50b8bad39e7e1afd3e4e9c2b7dd145fad07501 # v1.8.0
        with:
          auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
          gistID: 5e90d640f8c212ab7bbac38f72323f80
          filename: pytest-coverage-comment__main.json
          label: coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: typescript
